title: "Shipon's Portfolio"
description: "A blog about my personal thoughts, experiences, and projects."
permalink: pretty
url: "https://shipon.top"
image: "https://avatars.githubusercontent.com/u/186933450?v=4"
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
remote_theme: jekyll/minima@v2.5.1
future: true
github_username: shorifsimec

# Disable automatic titles from markdown headers
titles_from_headings:
  enabled: false

# Facebook Open Graph Configuration
facebook:
  app_id: "1988062861858816"
